// Code generated by MockGen. DO NOT EDIT.
// Source: event_service.go
//
// Generated by this command:
//
//	mockgen -source=event_service.go -destination=../../service/mocks/event_service_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/DenysShpak0116/TuneWave/packages/server/internal/core/domain/models"
	query "github.com/DenysShpak0116/TuneWave/packages/server/internal/core/helpers/query"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// CountWhere mocks base method.
func (m *MockEventService) CountWhere(ctx context.Context, params *models.Event) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWhere", ctx, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWhere indicates an expected call of CountWhere.
func (mr *MockEventServiceMockRecorder) CountWhere(ctx, params any) *MockEventServiceCountWhereCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWhere", reflect.TypeOf((*MockEventService)(nil).CountWhere), ctx, params)
	return &MockEventServiceCountWhereCall{Call: call}
}

// MockEventServiceCountWhereCall wrap *gomock.Call
type MockEventServiceCountWhereCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceCountWhereCall) Return(arg0 int64, arg1 error) *MockEventServiceCountWhereCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceCountWhereCall) Do(f func(context.Context, *models.Event) (int64, error)) *MockEventServiceCountWhereCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceCountWhereCall) DoAndReturn(f func(context.Context, *models.Event) (int64, error)) *MockEventServiceCountWhereCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockEventService) Create(ctx context.Context, entities ...*models.Event) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range entities {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventServiceMockRecorder) Create(ctx any, entities ...any) *MockEventServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, entities...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventService)(nil).Create), varargs...)
	return &MockEventServiceCreateCall{Call: call}
}

// MockEventServiceCreateCall wrap *gomock.Call
type MockEventServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceCreateCall) Return(arg0 error) *MockEventServiceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceCreateCall) Do(f func(context.Context, ...*models.Event) error) *MockEventServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceCreateCall) DoAndReturn(f func(context.Context, ...*models.Event) error) *MockEventServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockEventService) Delete(ctx context.Context, id ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range id {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventServiceMockRecorder) Delete(ctx any, id ...any) *MockEventServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, id...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventService)(nil).Delete), varargs...)
	return &MockEventServiceDeleteCall{Call: call}
}

// MockEventServiceDeleteCall wrap *gomock.Call
type MockEventServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceDeleteCall) Return(arg0 error) *MockEventServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceDeleteCall) Do(f func(context.Context, ...uuid.UUID) error) *MockEventServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceDeleteCall) DoAndReturn(f func(context.Context, ...uuid.UUID) error) *MockEventServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// First mocks base method.
func (m *MockEventService) First(ctx context.Context, params *models.Event, preloads ...string) (*models.Event, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range preloads {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "First", varargs...)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockEventServiceMockRecorder) First(ctx, params any, preloads ...any) *MockEventServiceFirstCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, preloads...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockEventService)(nil).First), varargs...)
	return &MockEventServiceFirstCall{Call: call}
}

// MockEventServiceFirstCall wrap *gomock.Call
type MockEventServiceFirstCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceFirstCall) Return(arg0 *models.Event, arg1 error) *MockEventServiceFirstCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceFirstCall) Do(f func(context.Context, *models.Event, ...string) (*models.Event, error)) *MockEventServiceFirstCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceFirstCall) DoAndReturn(f func(context.Context, *models.Event, ...string) (*models.Event, error)) *MockEventServiceFirstCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockEventService) GetByID(ctx context.Context, id uuid.UUID, preloads ...string) (*models.Event, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range preloads {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventServiceMockRecorder) GetByID(ctx, id any, preloads ...any) *MockEventServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, preloads...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventService)(nil).GetByID), varargs...)
	return &MockEventServiceGetByIDCall{Call: call}
}

// MockEventServiceGetByIDCall wrap *gomock.Call
type MockEventServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceGetByIDCall) Return(arg0 *models.Event, arg1 error) *MockEventServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceGetByIDCall) Do(f func(context.Context, uuid.UUID, ...string) (*models.Event, error)) *MockEventServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceGetByIDCall) DoAndReturn(f func(context.Context, uuid.UUID, ...string) (*models.Event, error)) *MockEventServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Last mocks base method.
func (m *MockEventService) Last(ctx context.Context, params *models.Event, preloads ...string) (*models.Event, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range preloads {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Last", varargs...)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Last indicates an expected call of Last.
func (mr *MockEventServiceMockRecorder) Last(ctx, params any, preloads ...any) *MockEventServiceLastCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, preloads...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockEventService)(nil).Last), varargs...)
	return &MockEventServiceLastCall{Call: call}
}

// MockEventServiceLastCall wrap *gomock.Call
type MockEventServiceLastCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceLastCall) Return(arg0 *models.Event, arg1 error) *MockEventServiceLastCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceLastCall) Do(f func(context.Context, *models.Event, ...string) (*models.Event, error)) *MockEventServiceLastCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceLastCall) DoAndReturn(f func(context.Context, *models.Event, ...string) (*models.Event, error)) *MockEventServiceLastCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockEventService) Update(ctx context.Context, entity *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEventServiceMockRecorder) Update(ctx, entity any) *MockEventServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventService)(nil).Update), ctx, entity)
	return &MockEventServiceUpdateCall{Call: call}
}

// MockEventServiceUpdateCall wrap *gomock.Call
type MockEventServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceUpdateCall) Return(arg0 error) *MockEventServiceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceUpdateCall) Do(f func(context.Context, *models.Event) error) *MockEventServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceUpdateCall) DoAndReturn(f func(context.Context, *models.Event) error) *MockEventServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Where mocks base method.
func (m *MockEventService) Where(ctx context.Context, params *models.Event, opts ...query.Option) ([]models.Event, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].([]models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Where indicates an expected call of Where.
func (mr *MockEventServiceMockRecorder) Where(ctx, params any, opts ...any) *MockEventServiceWhereCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockEventService)(nil).Where), varargs...)
	return &MockEventServiceWhereCall{Call: call}
}

// MockEventServiceWhereCall wrap *gomock.Call
type MockEventServiceWhereCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventServiceWhereCall) Return(arg0 []models.Event, arg1 error) *MockEventServiceWhereCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventServiceWhereCall) Do(f func(context.Context, *models.Event, ...query.Option) ([]models.Event, error)) *MockEventServiceWhereCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventServiceWhereCall) DoAndReturn(f func(context.Context, *models.Event, ...query.Option) ([]models.Event, error)) *MockEventServiceWhereCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
