// Code generated by MockGen. DO NOT EDIT.
// Source: file_storage.go
//
// Generated by this command:
//
//	mockgen -source=file_storage.go -destination=../../adapter/repository/mocks/file_storage_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFileStorage) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFileStorageMockRecorder) Get(ctx, key any) *MockFileStorageGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileStorage)(nil).Get), ctx, key)
	return &MockFileStorageGetCall{Call: call}
}

// MockFileStorageGetCall wrap *gomock.Call
type MockFileStorageGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageGetCall) Return(arg0 []byte, arg1 error) *MockFileStorageGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageGetCall) Do(f func(context.Context, string) ([]byte, error)) *MockFileStorageGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageGetCall) DoAndReturn(f func(context.Context, string) ([]byte, error)) *MockFileStorageGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockFileStorage) Remove(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFileStorageMockRecorder) Remove(ctx, key any) *MockFileStorageRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFileStorage)(nil).Remove), ctx, key)
	return &MockFileStorageRemoveCall{Call: call}
}

// MockFileStorageRemoveCall wrap *gomock.Call
type MockFileStorageRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageRemoveCall) Return(arg0 error) *MockFileStorageRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageRemoveCall) Do(f func(context.Context, string) error) *MockFileStorageRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageRemoveCall) DoAndReturn(f func(context.Context, string) error) *MockFileStorageRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockFileStorage) Save(ctx context.Context, key string, buf bytes.Buffer) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, key, buf)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockFileStorageMockRecorder) Save(ctx, key, buf any) *MockFileStorageSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFileStorage)(nil).Save), ctx, key, buf)
	return &MockFileStorageSaveCall{Call: call}
}

// MockFileStorageSaveCall wrap *gomock.Call
type MockFileStorageSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileStorageSaveCall) Return(arg0 string, arg1 error) *MockFileStorageSaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileStorageSaveCall) Do(f func(context.Context, string, bytes.Buffer) (string, error)) *MockFileStorageSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileStorageSaveCall) DoAndReturn(f func(context.Context, string, bytes.Buffer) (string, error)) *MockFileStorageSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
