// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../adapter/repository/mocks/repository_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	port "github.com/DenysShpak0116/TuneWave/packages/server/internal/core/port"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuery is a mock of Query interface.
type MockQuery[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder[T]
	isgomock struct{}
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder[T any] struct {
	mock *MockQuery[T]
}

// NewMockQuery creates a new mock instance.
func NewMockQuery[T any](ctrl *gomock.Controller) *MockQuery[T] {
	mock := &MockQuery[T]{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery[T]) EXPECT() *MockQueryMockRecorder[T] {
	return m.recorder
}

// Count mocks base method.
func (m *MockQuery[T]) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockQueryMockRecorder[T]) Count() *MockQueryCountCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockQuery[T])(nil).Count))
	return &MockQueryCountCall[T]{Call: call}
}

// MockQueryCountCall wrap *gomock.Call
type MockQueryCountCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryCountCall[T]) Return(arg0 int64, arg1 error) *MockQueryCountCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryCountCall[T]) Do(f func() (int64, error)) *MockQueryCountCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryCountCall[T]) DoAndReturn(f func() (int64, error)) *MockQueryCountCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockQuery[T]) Delete() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueryMockRecorder[T]) Delete() *MockQueryDeleteCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuery[T])(nil).Delete))
	return &MockQueryDeleteCall[T]{Call: call}
}

// MockQueryDeleteCall wrap *gomock.Call
type MockQueryDeleteCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryDeleteCall[T]) Return(arg0 error) *MockQueryDeleteCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryDeleteCall[T]) Do(f func() error) *MockQueryDeleteCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryDeleteCall[T]) DoAndReturn(f func() error) *MockQueryDeleteCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockQuery[T]) Find() ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find")
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockQueryMockRecorder[T]) Find() *MockQueryFindCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockQuery[T])(nil).Find))
	return &MockQueryFindCall[T]{Call: call}
}

// MockQueryFindCall wrap *gomock.Call
type MockQueryFindCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryFindCall[T]) Return(arg0 []T, arg1 error) *MockQueryFindCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryFindCall[T]) Do(f func() ([]T, error)) *MockQueryFindCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryFindCall[T]) DoAndReturn(f func() ([]T, error)) *MockQueryFindCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// First mocks base method.
func (m *MockQuery[T]) First(params any, args ...any) (T, error) {
	m.ctrl.T.Helper()
	varargs := []any{params}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "First", varargs...)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *MockQueryMockRecorder[T]) First(params any, args ...any) *MockQueryFirstCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{params}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockQuery[T])(nil).First), varargs...)
	return &MockQueryFirstCall[T]{Call: call}
}

// MockQueryFirstCall wrap *gomock.Call
type MockQueryFirstCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryFirstCall[T]) Return(arg0 T, arg1 error) *MockQueryFirstCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryFirstCall[T]) Do(f func(any, ...any) (T, error)) *MockQueryFirstCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryFirstCall[T]) DoAndReturn(f func(any, ...any) (T, error)) *MockQueryFirstCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Group mocks base method.
func (m *MockQuery[T]) Group(group string) port.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", group)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Group indicates an expected call of Group.
func (mr *MockQueryMockRecorder[T]) Group(group any) *MockQueryGroupCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockQuery[T])(nil).Group), group)
	return &MockQueryGroupCall[T]{Call: call}
}

// MockQueryGroupCall wrap *gomock.Call
type MockQueryGroupCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryGroupCall[T]) Return(arg0 port.Query[T]) *MockQueryGroupCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryGroupCall[T]) Do(f func(string) port.Query[T]) *MockQueryGroupCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryGroupCall[T]) DoAndReturn(f func(string) port.Query[T]) *MockQueryGroupCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Join mocks base method.
func (m *MockQuery[T]) Join(query string, args ...any) port.Query[T] {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockQueryMockRecorder[T]) Join(query any, args ...any) *MockQueryJoinCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockQuery[T])(nil).Join), varargs...)
	return &MockQueryJoinCall[T]{Call: call}
}

// MockQueryJoinCall wrap *gomock.Call
type MockQueryJoinCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryJoinCall[T]) Return(arg0 port.Query[T]) *MockQueryJoinCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryJoinCall[T]) Do(f func(string, ...any) port.Query[T]) *MockQueryJoinCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryJoinCall[T]) DoAndReturn(f func(string, ...any) port.Query[T]) *MockQueryJoinCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Last mocks base method.
func (m *MockQuery[T]) Last(params any, args ...any) (T, error) {
	m.ctrl.T.Helper()
	varargs := []any{params}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Last", varargs...)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Last indicates an expected call of Last.
func (mr *MockQueryMockRecorder[T]) Last(params any, args ...any) *MockQueryLastCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{params}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockQuery[T])(nil).Last), varargs...)
	return &MockQueryLastCall[T]{Call: call}
}

// MockQueryLastCall wrap *gomock.Call
type MockQueryLastCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryLastCall[T]) Return(arg0 T, arg1 error) *MockQueryLastCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryLastCall[T]) Do(f func(any, ...any) (T, error)) *MockQueryLastCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryLastCall[T]) DoAndReturn(f func(any, ...any) (T, error)) *MockQueryLastCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Order mocks base method.
func (m *MockQuery[T]) Order(order string) port.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Order", order)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Order indicates an expected call of Order.
func (mr *MockQueryMockRecorder[T]) Order(order any) *MockQueryOrderCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Order", reflect.TypeOf((*MockQuery[T])(nil).Order), order)
	return &MockQueryOrderCall[T]{Call: call}
}

// MockQueryOrderCall wrap *gomock.Call
type MockQueryOrderCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryOrderCall[T]) Return(arg0 port.Query[T]) *MockQueryOrderCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryOrderCall[T]) Do(f func(string) port.Query[T]) *MockQueryOrderCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryOrderCall[T]) DoAndReturn(f func(string) port.Query[T]) *MockQueryOrderCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Preload mocks base method.
func (m *MockQuery[T]) Preload(preloads ...string) port.Query[T] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range preloads {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Preload", varargs...)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Preload indicates an expected call of Preload.
func (mr *MockQueryMockRecorder[T]) Preload(preloads ...any) *MockQueryPreloadCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preload", reflect.TypeOf((*MockQuery[T])(nil).Preload), preloads...)
	return &MockQueryPreloadCall[T]{Call: call}
}

// MockQueryPreloadCall wrap *gomock.Call
type MockQueryPreloadCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryPreloadCall[T]) Return(arg0 port.Query[T]) *MockQueryPreloadCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryPreloadCall[T]) Do(f func(...string) port.Query[T]) *MockQueryPreloadCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryPreloadCall[T]) DoAndReturn(f func(...string) port.Query[T]) *MockQueryPreloadCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Skip mocks base method.
func (m *MockQuery[T]) Skip(offset int) port.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skip", offset)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Skip indicates an expected call of Skip.
func (mr *MockQueryMockRecorder[T]) Skip(offset any) *MockQuerySkipCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*MockQuery[T])(nil).Skip), offset)
	return &MockQuerySkipCall[T]{Call: call}
}

// MockQuerySkipCall wrap *gomock.Call
type MockQuerySkipCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuerySkipCall[T]) Return(arg0 port.Query[T]) *MockQuerySkipCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuerySkipCall[T]) Do(f func(int) port.Query[T]) *MockQuerySkipCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuerySkipCall[T]) DoAndReturn(f func(int) port.Query[T]) *MockQuerySkipCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Take mocks base method.
func (m *MockQuery[T]) Take(limit int) port.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", limit)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Take indicates an expected call of Take.
func (mr *MockQueryMockRecorder[T]) Take(limit any) *MockQueryTakeCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockQuery[T])(nil).Take), limit)
	return &MockQueryTakeCall[T]{Call: call}
}

// MockQueryTakeCall wrap *gomock.Call
type MockQueryTakeCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryTakeCall[T]) Return(arg0 port.Query[T]) *MockQueryTakeCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryTakeCall[T]) Do(f func(int) port.Query[T]) *MockQueryTakeCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryTakeCall[T]) DoAndReturn(f func(int) port.Query[T]) *MockQueryTakeCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Where mocks base method.
func (m *MockQuery[T]) Where(params any, args ...any) port.Query[T] {
	m.ctrl.T.Helper()
	varargs := []any{params}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockQueryMockRecorder[T]) Where(params any, args ...any) *MockQueryWhereCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{params}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockQuery[T])(nil).Where), varargs...)
	return &MockQueryWhereCall[T]{Call: call}
}

// MockQueryWhereCall wrap *gomock.Call
type MockQueryWhereCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQueryWhereCall[T]) Return(arg0 port.Query[T]) *MockQueryWhereCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQueryWhereCall[T]) Do(f func(any, ...any) port.Query[T]) *MockQueryWhereCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQueryWhereCall[T]) DoAndReturn(f func(any, ...any) port.Query[T]) *MockQueryWhereCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepository is a mock of Repository interface.
type MockRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[T any] struct {
	mock *MockRepository[T]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[T any](ctrl *gomock.Controller) *MockRepository[T] {
	mock := &MockRepository[T]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[T]) EXPECT() *MockRepositoryMockRecorder[T] {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepository[T]) Add(ctx context.Context, entities ...*T) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range entities {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryMockRecorder[T]) Add(ctx any, entities ...any) *MockRepositoryAddCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, entities...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepository[T])(nil).Add), varargs...)
	return &MockRepositoryAddCall[T]{Call: call}
}

// MockRepositoryAddCall wrap *gomock.Call
type MockRepositoryAddCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryAddCall[T]) Return(arg0 error) *MockRepositoryAddCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryAddCall[T]) Do(f func(context.Context, ...*T) error) *MockRepositoryAddCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryAddCall[T]) DoAndReturn(f func(context.Context, ...*T) error) *MockRepositoryAddCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockRepository[T]) Delete(ctx context.Context, id ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range id {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[T]) Delete(ctx any, id ...any) *MockRepositoryDeleteCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, id...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[T])(nil).Delete), varargs...)
	return &MockRepositoryDeleteCall[T]{Call: call}
}

// MockRepositoryDeleteCall wrap *gomock.Call
type MockRepositoryDeleteCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteCall[T]) Return(arg0 error) *MockRepositoryDeleteCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteCall[T]) Do(f func(context.Context, ...uuid.UUID) error) *MockRepositoryDeleteCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteCall[T]) DoAndReturn(f func(context.Context, ...uuid.UUID) error) *MockRepositoryDeleteCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Distinct mocks base method.
func (m *MockRepository[T]) Distinct(ctx context.Context, field string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distinct", ctx, field)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Distinct indicates an expected call of Distinct.
func (mr *MockRepositoryMockRecorder[T]) Distinct(ctx, field any) *MockRepositoryDistinctCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distinct", reflect.TypeOf((*MockRepository[T])(nil).Distinct), ctx, field)
	return &MockRepositoryDistinctCall[T]{Call: call}
}

// MockRepositoryDistinctCall wrap *gomock.Call
type MockRepositoryDistinctCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDistinctCall[T]) Return(arg0 []string) *MockRepositoryDistinctCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDistinctCall[T]) Do(f func(context.Context, string) []string) *MockRepositoryDistinctCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDistinctCall[T]) DoAndReturn(f func(context.Context, string) []string) *MockRepositoryDistinctCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewQuery mocks base method.
func (m *MockRepository[T]) NewQuery(ctx context.Context) port.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewQuery", ctx)
	ret0, _ := ret[0].(port.Query[T])
	return ret0
}

// NewQuery indicates an expected call of NewQuery.
func (mr *MockRepositoryMockRecorder[T]) NewQuery(ctx any) *MockRepositoryNewQueryCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewQuery", reflect.TypeOf((*MockRepository[T])(nil).NewQuery), ctx)
	return &MockRepositoryNewQueryCall[T]{Call: call}
}

// MockRepositoryNewQueryCall wrap *gomock.Call
type MockRepositoryNewQueryCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryNewQueryCall[T]) Return(arg0 port.Query[T]) *MockRepositoryNewQueryCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryNewQueryCall[T]) Do(f func(context.Context) port.Query[T]) *MockRepositoryNewQueryCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryNewQueryCall[T]) DoAndReturn(f func(context.Context) port.Query[T]) *MockRepositoryNewQueryCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockRepository[T]) Update(ctx context.Context, entity *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[T]) Update(ctx, entity any) *MockRepositoryUpdateCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[T])(nil).Update), ctx, entity)
	return &MockRepositoryUpdateCall[T]{Call: call}
}

// MockRepositoryUpdateCall wrap *gomock.Call
type MockRepositoryUpdateCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateCall[T]) Return(arg0 error) *MockRepositoryUpdateCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateCall[T]) Do(f func(context.Context, *T) error) *MockRepositoryUpdateCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateCall[T]) DoAndReturn(f func(context.Context, *T) error) *MockRepositoryUpdateCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
